name: docker

on:
  workflow_dispatch:
  push:
    tags: ['v*']
  pull_request:

env:
  BUILD_TARGET: scanservjs-core
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/scanservjs
          tags: |
            type=schedule,pattern=staging
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          target: ${{ env.BUILD_TARGET }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
